name: run config.py

on:
  push:
      branches:
        - main
  schedule:
    - cron: "*/15 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
      
    permissions:
      contents: write

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script
        run: |
          python config.py

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@github.com"

      - name: Sync with remote
        run: |
          git pull --rebase origin main
        continue-on-error: true
          
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto: update config"
          skip_fetch: false
          skip_checkout: false
